spring:
  datasource:
    url: jdbc:mysql://43.201.67.47:3306/umc7th?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post  # spring이 kakao에 client 자격 증명을 post 방식으로 전달
            client-id: 7f61446222bedb30939ce2254d3b6614
            client-secret: QVYU1G1GAYmQoTjYzwBeFA9QDI46pLFz
            redirect-uri: http://43.201.67.47:8080/login/oauth2/code/kakao # 인증 후 kakao가 사용자를 리다이렉트할 url
            authorization-grant-type: authorization_code  # 사용할 OAuth 2.0 흐름: 웹 application 표준 흐름
            scope: profile_nickname # app이 요청하는 권한
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # 사용자가 kakao로 로그인하기 위해 리다이렉트되는 url
            token-uri: https://kauth.kakao.com/oauth/token  # application이 인증 코드를 액세스 토큰으로 교환하는 url
            user-info-uri: https://kapi.kakao.com/v2/user/me  # application이 액세스 토큰을 사용하여 사용자 정보를 가져올 수 있는 url
            user-name-attribute: id # 사용자 정보 응답에서 주요 이름으로 사용할 속성